$sku, $product_name, $fabric_name, $model, $model, $model, $model, $model, $is_new, $available_in_showroom, $available_for_delivery_2, $carousel_item_1,
$carousel_item_2,
$carousel_item_3,
$carousel_item_4,
$carousel_item_5,
$right_sofa_piece, $fabric_name, $model, $model, $model, $model, $model, $is_new, $available_in_showroom, $available_for_delivery_2,
$carousel_item_1_mob,
$carousel_item_2_mob,
$carousel_item_3_mob,
$carousel_item_4_mob,
$carousel_item_5_mob,
$product_full_name, $price_sale, $price, $product_full_name, $price_sale, $price, $description, $prod_width,
$prod_depth,
$prod_height,
$prod_weight, $prod_seat_height,
$prod_seat_width,
$prod_seat_depth,
$prod_back_width, $product_type, $transform_type, $matress_type,
$product_form,
$product_style, $product_inside,
$features, $product_fabric_about,
$product_fabric_img, $description, $prod_width,
$prod_depth,
$prod_height,
$prod_weight, $prod_seat_height,
$prod_seat_width,
$prod_seat_depth,
$prod_back_width, $product_type, $transform_type, $matress_type,
$product_form,
$product_style, $product_inside,
$features, $product_fabric_about,
$product_fabric_img